### ISSUE TITLE
'HAL_Pin_Map' was not declared in this scope;

### ISSUE THREAD

**Issue by reparke** [technobly/Particle-NeoPixel#43]
I'm using an Argon on DeviceOS 5.0, and when I compile this library, I get the following error:

`lib/neopixel/src/neopixel.cpp:67:30: error: 'HAL_Pin_Map' was not declared in this scope; did you mean 'Hal_Pin_Map'?`

I fixed the issue by changing line 67 from
`NRF5x_Pin_Info* PIN_MAP2 = HAL_Pin_Map();`
to
`NRF5x_Pin_Info* PIN_MAP2 = Hal_Pin_Map();`

I believe the platform id isn't the issue so I'm thinking it's the Device OS version.

**Comment by grillinmuffins** [comment]
Yep I'm seeing this error as well with 5.0 and 5.1

**Comment by technobly** [comment]
Fixed with v1.0.1, thanks!  Should be released soon.
